# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gd_cpp <- function(x, y, alpha, iterations) {
    .Call('_GDstepper_gd_cpp', PACKAGE = 'GDstepper', x, y, alpha, iterations)
}

